const nome = "Lucas";
const idade = 16;
const cidade = "São Paulo";
const atividade = "jogos";
const aprender = "desenvolvimento de aplicativos";
const area = "tecnologia";
const mensagem = "Estou evoluindo na programação!";
const desafio = "Criar um aplicativo completo do zero";

console.log("===================================");
console.log("          MEU APLICATIVO");
console.log("===================================");
console.log(`Nome: ${nome}`);
console.log(`Idade: ${idade}`);
console.log(`Cidade: ${cidade}`);
console.log(`Atividade de interesse: ${atividade}`);
console.log(`Quero aprender: ${aprender}`);
console.log(`Área de interesse: ${area}`);
console.log(`Mensagem: ${mensagem}`);
console.log(`Desafio: ${desafio}`);